# Generated by Django 4.2 on 2023-04-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credits', models.IntegerField()),
                ('instructor', models.CharField(max_length=255)),
                ('day', models.CharField(max_length=255)),
                ('time', models.TimeField(verbose_name='')),
                ('room', models.CharField(max_length=10)),
                ('Major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.major')),
            ],
        ),
    ]
