# Generated by Django 4.2 on 2023-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='requiredecredits',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
