# Generated by Django 4.2 on 2023-04-09 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('start_time',)},
        ),
    ]
